### ISSUE TITLE
rgba(#000, .3);

### ISSUE THREAD

**Issue by dreiv** [Haufe-Lexware/Scss-Styleguide#2]
Your suggestion to use `rgba(#000, .3);` instead of `rgba(255,255,255,.3);`
looks good, but it is not a legal syntax according to the [CSS specification](https://www.w3schools.com/cssref/css_colors_legal.asp) and does not render in the browsers.

You could change the example to another.

**Comment by timhartmann** [comment]
@dreiv Thank you for the hint. If we would write CSS, then I would agree. Because of we using a pre-compiler, HEX-Codes in .scss files are possible. After Sass compiled the files, we have a RGB value in the CSS file
